Pin node version
digicatapult/vitalam-identity-service pull request #7
Opened 2022-01-31 16:00 UTC by danielcooperxyz

Update and pin the node version

2022-01-31 16:05 UTC, jonmattgray approved these changes

2022-01-31 16:06 UTC, darrylmorton-digicatapult approved these changes

2022-01-31 17:50 UTC, n3op2 approved these changes

2022-02-02 08:24 UTC, dblane-digicatapult requested changes
please pin npm version in workflows

2022-02-02 09:11 UTC, dblane-digicatapult approved these changes

2022-02-02 09:32 UTC, mattdean-digicatapult approved these changes

2022-02-02 09:41 UTC, merged